project_name: "test_whole_model"
dataset: "cifar"
batch_size: 128
checkpoint: 'runs/cluster_checkpoints/cifar_100_500.ckpt'
closeness_factor: 0.6
train_split_name: 'train'
test_split_name: 'test'
max_epochs: 7
switch_epoch: 3
alpha: 0.9
lr: 3e-4
checkpoint_epoch_interval: 2
pretraining: False
pretraining_checkpoint: 'runs/test_u_net_conditional_cifar_closeness0.6/kdbpklv6/checkpoints/c2ae-epoch=09-condition_difference=0.13.ckpt'
