project_name: "test_tiny_classification_pretraining"
dataset: "svhn"
batch_size: 128
checkpoint: 'tests/runs/cluster_checkpoints/svhn_100_500_3.ckpt'
closeness_factor: 0.6
train_split_name: 'train'
test_split_name: 'test'
max_epochs: 20
switch_epoch: 20
alpha: 0.9
lr: 3e-4
checkpoint_epoch_interval: 20
