project_name: "test_wide_net"
dataset: "tiny"
architecture: 'simple'
batch_size: 128
checkpoint: 'tests/runs/cluster_checkpoints/tiny_10_120_simple_normalized.ckpt'
closeness_factor: 0.1
train_split_name: 'train'
test_split_name: 'valid'
max_epochs: 10
switch_epoch: 1
alpha: 0.9
lr: 3e-4
checkpoint_epoch_interval: 8
augmented: False
