project_name: "test_weight_transfer"
dataset: "cifar"
architecture: 'widenet'
batch_size: 64
checkpoint: 'tests/runs/cluster_checkpoints/cifar_10_120_small_unet_003_early_epoch.ckpt'
closeness_factor: 0.6
train_split_name: 'train'
test_split_name: 'test'
max_epochs: 10
switch_epoch: 1
alpha: 0.9
lr: 3e-4
checkpoint_epoch_interval: 5
augmented: False
pretraining_checkpoint: 'tests/runs/contrastive_pretraining/contrastive_learning.ckpt'
