project_name: "test_simple_with_x32"
dataset: "cifar"
architecture: 'widenet'
batch_size: 128
checkpoint: 'tests/runs/cluster_checkpoints/original_unet_cifar.ckpt'
closeness_factor: 0.6
train_split_name: 'train'
test_split_name: 'test'
max_epochs: 15
switch_epoch: 5
alpha: 0.9
lr: 3e-4
checkpoint_epoch_interval: 5
augmented: False
pretraining_checkpoint: null
