project_name: "test_simple_normalized"
dataset: "mnist"
architecture: 'simple'
batch_size: 128
checkpoint: 'tests/runs/cluster_checkpoints/mnist_10_120_simple_normalized.ckpt'
closeness_factor: 0.6
train_split_name: 'train'
test_split_name: 'test'
max_epochs: 10
switch_epoch: 1
alpha: 0.9
lr: 3e-4
checkpoint_epoch_interval: 8
