project_name: "test_automatic_osr"
dataset: "cifar"
architecture: 'unet'
batch_size: 128
checkpoint: 'tests/runs/cluster_checkpoints/original_unet_cifar.ckpt'
chosen_classes: [0, 1, 2, 3, 4, 5, 6]
train_split_name: 'train'
test_split_name: 'test'
max_epochs: 1
switch_epoch: 1
alpha: 0.9
lr: 3e-4
checkpoint_epoch_interval: 5
augmented: False
pretraining_checkpoint: null
calculate_osr: True
