project_name: "test_wide_net"
dataset: "cifar"
architecture: 'widenet'
batch_size: 32
checkpoint: 'tests/runs/cluster_checkpoints/cifar_widenet_12_120.ckpt'
closeness_factor: 0.6
train_split_name: 'train'
test_split_name: 'test'
max_epochs: 10
switch_epoch: 1
alpha: 0.9
lr: 3e-4
checkpoint_epoch_interval: 8
